from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

SCRIPT_DIR = Path(__file__).resolve().parent

import sys

if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from blender_convert import SUPPORTED_EXTS  # noqa: E402
from common import save_json  # noqa: E402
from linker_oracle import parse_load_zones, sanitize_name  # noqa: E402


def collect_sources(path: Path, max_files: int) -> List[Path]:
    if path.is_file():
        files = [path]
    elif path.is_dir():
        files = sorted([item for item in path.rglob("*") if item.is_file() and item.suffix.lower() in SUPPORTED_EXTS])
    else:
        files = []
    if max_files > 0:
        files = files[:max_files]
    return files


def load_profiles(path: Path) -> List[Dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    profiles = payload.get("profiles", [])
    if not isinstance(profiles, list) or not profiles:
        raise ValueError(f"No profiles found in {path}")
    normalized: List[Dict[str, Any]] = []
    for item in profiles:
        name = str(item.get("name", "")).strip()
        if not name:
            continue
        normalized.append(
            {
                "name": sanitize_name(name),
                "decimate_ratio": float(item.get("decimate_ratio", 0.45)),
                "max_bones": int(item.get("max_bones", 128)),
                "max_weights": int(item.get("max_weights", 4)),
            }
        )
    if not normalized:
        raise ValueError(f"Profiles are invalid in {path}")
    return normalized


def run_cmd(command: Sequence[str]) -> Tuple[int, str]:
    proc = subprocess.run(command, capture_output=True, text=True, check=False)
    output = (proc.stdout or "") + ("\n" + proc.stderr if proc.stderr else "")
    return proc.returncode, output


def find_single_xmodel(report_path: Path) -> Path:
    payload = json.loads(report_path.read_text(encoding="utf-8"))
    rows = payload.get("rows", [])
    ok_rows = [row for row in rows if row.get("status") == "ok" and row.get("xmodel_json")]
    if not ok_rows:
        raise RuntimeError(f"No converted xmodel found in report: {report_path}")
    return Path(ok_rows[0]["xmodel_json"]).resolve()


def score_trial(oracle_payload: Dict[str, Any], decimate_ratio: float) -> float:
    linker = oracle_payload.get("linker", {})
    status = str(linker.get("status", "fail"))
    errors = linker.get("errors", []) or []
    warnings = linker.get("warnings", []) or []
    base = 10000.0 if status == "pass" else 0.0
    quality_bonus = decimate_ratio * 100.0
    penalty = float(len(errors) * 100 + len(warnings) * 10)
    return base + quality_bonus - penalty


def write_zone(zone_path: Path, asset_names: Sequence[str]) -> None:
    zone_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// Auto-generated by auto_tune_conversion.py", ">game,T6", ""]
    lines.extend([f"xmodel,{name}" for name in sorted(set(asset_names))])
    zone_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def next_non_conflicting(path: Path) -> Path:
    if not path.exists():
        return path
    stem = path.stem
    suffix = path.suffix
    parent = path.parent
    counter = 2
    while True:
        candidate = parent / f"{stem}_{counter}{suffix}"
        if not candidate.exists():
            return candidate
        counter += 1


def main() -> None:
    parser = argparse.ArgumentParser(description="Auto-tune conversion profiles via linker oracle feedback.")
    parser.add_argument("--input", required=True, help="Source mesh file or directory.")
    parser.add_argument(
        "--profiles",
        default="tools/asset_port_pipeline/conversion_profiles.json",
        help="JSON file containing conversion profiles.",
    )
    parser.add_argument("--project-name", default="bo3_ported_tuned", help="Final assembled project name.")
    parser.add_argument("--output-root", default="_build/asset_port_pipeline/tuned_zone_raw", help="Final output root.")
    parser.add_argument("--workspace", default="_build/asset_port_pipeline/auto_tune_workspace", help="Trial workspace root.")
    parser.add_argument("--blender-exe", default="blender", help="Path or command for blender.")
    parser.add_argument("--linker", default="tools/oat/Linker.exe", help="Path to Linker.exe")
    parser.add_argument(
        "--skeleton-map",
        default="tools/asset_port_pipeline/skeleton_map_bo3_to_bo2.json",
        help="Skeleton mapping json path.",
    )
    parser.add_argument(
        "--load-zones",
        nargs="*",
        default=["zone/all/common_zm.ff"],
        help="Zones to preload for linker oracle (supports semicolon-separated entries).",
    )
    parser.add_argument("--auto-resolve-missing", action="store_true", help="Enable dependency staging retries in linker oracle.")
    parser.add_argument("--max-retries", type=int, default=2, help="Max linker retries when auto-resolve is enabled.")
    parser.add_argument(
        "--dependency-roots",
        nargs="*",
        default=["zone_dump/zone_raw", "_build/t6_asset_dump/zone_raw"],
        help="Roots scanned for missing assets (supports semicolon-separated values).",
    )
    parser.add_argument("--max-files", type=int, default=0, help="Optional cap for quick runs.")
    parser.add_argument("--copy-glb-without-blender", action="store_true", help="Allow GLB passthrough when blender is missing.")
    parser.add_argument(
        "--report",
        default="_build/asset_port_pipeline/auto_tune_report.json",
        help="Output report path.",
    )
    args = parser.parse_args()

    repo_root = Path.cwd().resolve()
    input_path = Path(args.input)
    if not input_path.is_absolute():
        input_path = (repo_root / input_path).resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input not found: {input_path}")

    profiles_path = Path(args.profiles)
    if not profiles_path.is_absolute():
        profiles_path = (repo_root / profiles_path).resolve()
    if not profiles_path.exists():
        raise FileNotFoundError(f"Profiles file not found: {profiles_path}")
    profiles = load_profiles(profiles_path)

    linker_path = Path(args.linker)
    if not linker_path.is_absolute():
        linker_path = (repo_root / linker_path).resolve()
    if not linker_path.exists():
        raise FileNotFoundError(f"Linker not found: {linker_path}")

    skeleton_map = Path(args.skeleton_map)
    if not skeleton_map.is_absolute():
        skeleton_map = (repo_root / skeleton_map).resolve()
    if not skeleton_map.exists():
        raise FileNotFoundError(f"Skeleton map not found: {skeleton_map}")

    load_zone_items = parse_load_zones(args.load_zones)
    load_zone_paths: List[Path] = []
    for item in load_zone_items:
        path = Path(item)
        if not path.is_absolute():
            path = (repo_root / path).resolve()
        if not path.exists():
            raise FileNotFoundError(f"Missing load zone: {path}")
        load_zone_paths.append(path)

    dependency_root_items = parse_load_zones(args.dependency_roots)
    dependency_roots: List[Path] = []
    for item in dependency_root_items:
        path = Path(item)
        if not path.is_absolute():
            path = (repo_root / path).resolve()
        if path.exists():
            dependency_roots.append(path)

    sources = collect_sources(input_path, max_files=args.max_files)
    if not sources:
        raise FileNotFoundError(f"No supported source files found at: {input_path}")

    workspace = Path(args.workspace)
    if not workspace.is_absolute():
        workspace = (repo_root / workspace).resolve()
    workspace.mkdir(parents=True, exist_ok=True)

    output_root = Path(args.output_root)
    if not output_root.is_absolute():
        output_root = (repo_root / output_root).resolve()
    final_project = sanitize_name(args.project_name)
    final_root = output_root / final_project
    final_xmodel_dir = final_root / "xmodel"
    final_model_export_dir = final_root / "model_export"
    final_logs_dir = final_root / "_logs"
    final_xmodel_dir.mkdir(parents=True, exist_ok=True)
    final_model_export_dir.mkdir(parents=True, exist_ok=True)
    final_logs_dir.mkdir(parents=True, exist_ok=True)

    blender_convert_script = (SCRIPT_DIR / "blender_convert.py").resolve()
    linker_oracle_script = (SCRIPT_DIR / "linker_oracle.py").resolve()

    overall_rows: List[Dict[str, Any]] = []
    final_asset_names: List[str] = []

    for source_index, source in enumerate(sources, start=1):
        source_key = sanitize_name(source.stem)
        trial_rows: List[Dict[str, Any]] = []

        for profile in profiles:
            profile_name = profile["name"]
            trial_project = sanitize_name(f"{source_key}_{profile_name}")
            trial_output_root = workspace / "converted_trials"
            convert_report = workspace / "reports" / f"{trial_project}.convert.json"
            oracle_report = workspace / "reports" / f"{trial_project}.oracle.json"
            convert_report.parent.mkdir(parents=True, exist_ok=True)

            convert_cmd = [
                sys.executable,
                str(blender_convert_script),
                "--input",
                str(source),
                "--output-root",
                str(trial_output_root),
                "--project-name",
                trial_project,
                "--blender-exe",
                args.blender_exe,
                "--skeleton-map",
                str(skeleton_map),
                "--decimate-ratio",
                str(profile["decimate_ratio"]),
                "--max-bones",
                str(profile["max_bones"]),
                "--max-weights",
                str(profile["max_weights"]),
                "--report",
                str(convert_report),
                "--max-files",
                "1",
            ]
            if args.copy_glb_without_blender:
                convert_cmd.append("--copy-glb-without-blender")

            convert_exit, convert_log = run_cmd(convert_cmd)
            if convert_exit != 0:
                trial_rows.append(
                    {
                        "profile": profile,
                        "status": "convert_error",
                        "score": -1e9,
                        "convert_exit": convert_exit,
                        "convert_log": convert_log[-8000:],
                    }
                )
                continue

            try:
                trial_xmodel = find_single_xmodel(convert_report)
            except Exception as exc:
                trial_rows.append(
                    {
                        "profile": profile,
                        "status": "convert_error",
                        "score": -1e9,
                        "convert_exit": convert_exit,
                        "convert_log": convert_log[-8000:],
                        "error": str(exc),
                    }
                )
                continue

            oracle_cmd: List[str] = [
                sys.executable,
                str(linker_oracle_script),
                "--xmodels",
                str(trial_xmodel),
                "--project-name",
                trial_project,
                "--workspace",
                str(workspace / "oracle_trials"),
                "--linker",
                str(linker_path),
                "--output",
                str(oracle_report),
            ]
            if load_zone_paths:
                oracle_cmd.extend(["--load-zones"] + [str(path) for path in load_zone_paths])
            if args.auto_resolve_missing:
                oracle_cmd.extend(["--auto-resolve-missing", "--max-retries", str(max(0, args.max_retries))])
                if dependency_roots:
                    oracle_cmd.extend(["--dependency-roots"] + [str(path) for path in dependency_roots])

            oracle_exit, oracle_log = run_cmd(oracle_cmd)
            if oracle_exit != 0 or not oracle_report.exists():
                trial_rows.append(
                    {
                        "profile": profile,
                        "status": "oracle_error",
                        "score": -1e9,
                        "xmodel_json": str(trial_xmodel),
                        "oracle_exit": oracle_exit,
                        "oracle_log": oracle_log[-8000:],
                    }
                )
                continue

            oracle_payload = json.loads(oracle_report.read_text(encoding="utf-8"))
            score = score_trial(oracle_payload=oracle_payload, decimate_ratio=float(profile["decimate_ratio"]))
            trial_rows.append(
                {
                    "profile": profile,
                    "status": "ok",
                    "score": score,
                    "xmodel_json": str(trial_xmodel),
                    "oracle_report": str(oracle_report),
                    "oracle_status": oracle_payload.get("linker", {}).get("status", "fail"),
                    "oracle_exit_code": oracle_payload.get("linker", {}).get("exit_code", 1),
                    "oracle_errors": oracle_payload.get("linker", {}).get("errors", []),
                    "oracle_warnings": oracle_payload.get("linker", {}).get("warnings", []),
                }
            )

        if not trial_rows:
            overall_rows.append({"source": str(source), "status": "error", "error": "no profile trials executed"})
            continue

        best = max(trial_rows, key=lambda row: float(row.get("score", -1e9)))
        source_row: Dict[str, Any] = {
            "source": str(source),
            "trials": trial_rows,
            "selected": best,
        }

        if best.get("status") == "ok" and best.get("xmodel_json"):
            selected_xmodel = Path(best["xmodel_json"]).resolve()
            payload = json.loads(selected_xmodel.read_text(encoding="utf-8"))
            source_model_export_dir = selected_xmodel.parent.parent / "model_export"

            asset_name = sanitize_name(selected_xmodel.stem)
            target_xmodel_path = next_non_conflicting(final_xmodel_dir / f"{asset_name}.json")
            target_asset_name = target_xmodel_path.stem

            for lod in payload.get("lods", []):
                file_field = str(lod.get("file", ""))
                lod_src = source_model_export_dir / Path(file_field).name
                if not lod_src.exists():
                    raise FileNotFoundError(f"Missing staged lod file: {lod_src}")
                lod_dst_name = f"{target_asset_name}_{Path(file_field).name}"
                lod_dst = next_non_conflicting(final_model_export_dir / lod_dst_name)
                shutil.copy2(lod_src, lod_dst)
                lod["file"] = f"model_export/{lod_dst.name}"

            target_xmodel_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            final_asset_names.append(target_asset_name)

            source_row.update(
                {
                    "status": "selected",
                    "final_xmodel_json": str(target_xmodel_path),
                    "final_asset_name": target_asset_name,
                }
            )
        else:
            source_row.update({"status": "no_viable_profile"})

        overall_rows.append(source_row)
        if source_index % 10 == 0:
            print(f"processed {source_index}/{len(sources)} sources")

    write_zone(final_root / "zone_source" / f"{final_project}.zone", final_asset_names)

    report = {
        "input": str(input_path),
        "profiles": profiles,
        "load_zones": [str(path) for path in load_zone_paths],
        "auto_resolve_missing": args.auto_resolve_missing,
        "max_retries": max(0, args.max_retries),
        "dependency_roots": [str(path) for path in dependency_roots],
        "project_name": final_project,
        "final_project_root": str(final_root),
        "counts": {
            "sources": len(sources),
            "selected": sum(1 for row in overall_rows if row.get("status") == "selected"),
            "no_viable_profile": sum(1 for row in overall_rows if row.get("status") == "no_viable_profile"),
            "error": sum(1 for row in overall_rows if row.get("status") == "error"),
        },
        "rows": overall_rows,
    }

    report_path = Path(args.report)
    if not report_path.is_absolute():
        report_path = (repo_root / report_path).resolve()
    save_json(report_path, report)

    print(f"Saved auto-tune report: {report_path}")
    print(
        f"selected={report['counts']['selected']} "
        f"no_viable={report['counts']['no_viable_profile']} "
        f"errors={report['counts']['error']} "
        f"final_root={final_root}"
    )


if __name__ == "__main__":
    main()
