from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Sequence

SCRIPT_DIR = Path(__file__).resolve().parent

import sys

if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from common import save_json  # noqa: E402
from linker_oracle import sanitize_name  # noqa: E402


SUPPORTED_EXTS = {".fbx", ".obj", ".glb", ".gltf", ".dae"}


def collect_inputs(path: Path) -> List[Path]:
    if path.is_file():
        return [path]
    if not path.is_dir():
        return []
    return sorted([item for item in path.rglob("*") if item.is_file() and item.suffix.lower() in SUPPORTED_EXTS])


def choose_blender_executable(configured: str) -> str:
    candidates = [configured]
    if configured.lower() == "blender":
        candidates += [
            "C:\\Program Files\\Blender Foundation\\Blender 4.1\\blender.exe",
            "C:\\Program Files\\Blender Foundation\\Blender 4.0\\blender.exe",
            "C:\\Program Files\\Blender Foundation\\Blender 3.6\\blender.exe",
        ]
    for candidate in candidates:
        candidate_path = Path(candidate)
        if candidate_path.exists():
            return str(candidate_path)
        if shutil.which(candidate):
            return candidate
    return configured


def write_xmodel_descriptor(path: Path, model_file_rel: str, animated: bool) -> None:
    payload = {
        "$schema": "http://openassettools.dev/schema/xmodel.v1.json",
        "_game": "t6",
        "_type": "xmodel",
        "_version": 2,
        "collLod": 0,
        "flags": 0,
        "lightingOriginOffset": {"x": 0.0, "y": 0.0, "z": 0.5},
        "lightingOriginRange": 0.5,
        "lods": [{"distance": 900.0, "file": model_file_rel}],
        "type": "animated" if animated else "rigid",
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_zone_file(zone_path: Path, xmodel_names: Sequence[str]) -> None:
    zone_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Auto-generated by blender_convert.py",
        ">game,T6",
        "",
    ] + [f"xmodel,{name}" for name in sorted(set(xmodel_names))]
    zone_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def run_blender_worker(
    blender_exe: str,
    worker_path: Path,
    input_path: Path,
    output_glb: Path,
    skeleton_map: Path,
    decimate_ratio: float,
    max_bones: int,
    max_weights: int,
    max_submesh_vertices: int,
    metadata_out: Path,
) -> subprocess.CompletedProcess[str]:
    cmd = [
        blender_exe,
        "-b",
        "--factory-startup",
        "--python",
        str(worker_path),
        "--",
        "--input",
        str(input_path),
        "--output",
        str(output_glb),
        "--skeleton-map",
        str(skeleton_map),
        "--decimate-ratio",
        str(decimate_ratio),
        "--max-bones",
        str(max_bones),
        "--max-weights",
        str(max_weights),
        "--max-submesh-vertices",
        str(max_submesh_vertices),
        "--metadata-out",
        str(metadata_out),
    ]
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def fallback_copy_glb(input_path: Path, output_glb: Path, metadata_out: Path) -> None:
    output_glb.parent.mkdir(parents=True, exist_ok=True)
    if input_path.suffix.lower() == ".glb":
        shutil.copy2(input_path, output_glb)
    else:
        raise RuntimeError("Fallback copy mode only supports .glb inputs")
    payload = {
        "input": str(input_path),
        "output": str(output_glb),
        "has_armature": False,
        "source_has_armature": False,
        "kept_bones": [],
        "mesh_vertices": 0,
        "mesh_faces": 0,
        "vertex_group_count": 0,
        "source_mesh_vertices": 0,
        "source_mesh_faces": 0,
        "source_bounds": {"min": [0.0, 0.0, 0.0], "max": [0.0, 0.0, 0.0], "size": [0.0, 0.0, 0.0], "max_dim": 0.0},
        "output_bounds": {"min": [0.0, 0.0, 0.0], "max": [0.0, 0.0, 0.0], "size": [0.0, 0.0, 0.0], "max_dim": 0.0},
        "bbox_ratio_max_dim": 1.0,
        "split_stats": {"max_submesh_vertices": 0, "submesh_count": 0, "submesh_over_limit": 0},
        "rename_stats": {"renamed": 0, "unchanged": 0},
        "material_names": [],
        "bo2_bone_name_ratio": 0.0,
        "bo2_bone_name_count": 0,
        "tag_count": 0,
        "potential_unit_scale_issue": False,
        "fallback_copy_mode": True,
    }
    metadata_out.parent.mkdir(parents=True, exist_ok=True)
    metadata_out.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert source meshes into BO2 xmodel descriptor + GLB payloads.")
    parser.add_argument("--input", required=True, help="Input mesh file or folder (.fbx/.obj/.glb/.gltf/.dae).")
    parser.add_argument("--output-root", default="_build/asset_port_pipeline/converted_zone_raw", help="Output root.")
    parser.add_argument("--project-name", default="bo3_ported_assets", help="Output zone project name.")
    parser.add_argument("--blender-exe", default="blender", help="Path or command for blender executable.")
    parser.add_argument(
        "--skeleton-map",
        default="tools/asset_port_pipeline/skeleton_map_bo3_to_bo2.json",
        help="Skeleton mapping json file.",
    )
    parser.add_argument("--decimate-ratio", type=float, default=0.45, help="Blender decimation ratio.")
    parser.add_argument("--max-bones", type=int, default=128, help="Maximum bones to keep.")
    parser.add_argument("--max-weights", type=int, default=4, help="Maximum weights per vertex.")
    parser.add_argument("--max-submesh-vertices", type=int, default=2400, help="Target upper bound for submesh vertex count.")
    parser.add_argument("--verbose-worker", action="store_true", help="Print per-asset blender worker stdout/stderr.")
    parser.add_argument(
        "--copy-glb-without-blender",
        action="store_true",
        help="If blender is unavailable, allow .glb files to be copied through.",
    )
    parser.add_argument("--max-files", type=int, default=0, help="Optional cap for quick runs.")
    parser.add_argument("--report", default="_build/asset_port_pipeline/blender_convert_report.json", help="Output report path.")
    args = parser.parse_args()

    repo_root = Path.cwd().resolve()
    input_path = Path(args.input)
    if not input_path.is_absolute():
        input_path = (repo_root / input_path).resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input not found: {input_path}")

    output_root = Path(args.output_root)
    if not output_root.is_absolute():
        output_root = (repo_root / output_root).resolve()
    project = sanitize_name(args.project_name)
    project_root = output_root / project
    model_export_dir = project_root / "model_export"
    xmodel_dir = project_root / "xmodel"
    logs_dir = project_root / "_logs"
    model_export_dir.mkdir(parents=True, exist_ok=True)
    xmodel_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    skeleton_map = Path(args.skeleton_map)
    if not skeleton_map.is_absolute():
        skeleton_map = (repo_root / skeleton_map).resolve()
    if not skeleton_map.exists():
        raise FileNotFoundError(f"Skeleton map not found: {skeleton_map}")

    files = collect_inputs(input_path)
    if args.max_files > 0:
        files = files[: args.max_files]
    if not files:
        raise FileNotFoundError(f"No supported input files found at: {input_path}")

    blender_exe = choose_blender_executable(args.blender_exe)
    worker_path = (SCRIPT_DIR / "blender_worker.py").resolve()

    xmodel_names: List[str] = []
    rows: List[Dict[str, Any]] = []
    for idx, source in enumerate(files, start=1):
        name = sanitize_name(source.stem)
        glb_name = f"{name}_lod0.glb"
        output_glb = model_export_dir / glb_name
        metadata_out = logs_dir / f"{name}.metadata.json"
        stdout_log = logs_dir / f"{name}.stdout.log"
        stderr_log = logs_dir / f"{name}.stderr.log"

        row: Dict[str, Any] = {"source": str(source), "asset_name": name}
        try:
            if shutil.which(blender_exe) or Path(blender_exe).exists():
                proc = run_blender_worker(
                    blender_exe=blender_exe,
                    worker_path=worker_path,
                    input_path=source,
                    output_glb=output_glb,
                    skeleton_map=skeleton_map,
                    decimate_ratio=args.decimate_ratio,
                    max_bones=args.max_bones,
                    max_weights=args.max_weights,
                    max_submesh_vertices=args.max_submesh_vertices,
                    metadata_out=metadata_out,
                )
                stdout_log.write_text(proc.stdout or "", encoding="utf-8")
                stderr_log.write_text(proc.stderr or "", encoding="utf-8")
                if args.verbose_worker and (proc.stdout or proc.stderr):
                    print(f"[worker:{name}] exit={proc.returncode}")
                    if proc.stdout:
                        print(proc.stdout.rstrip())
                    if proc.stderr:
                        print(proc.stderr.rstrip())
                if proc.returncode != 0:
                    raise RuntimeError(f"blender failed exit={proc.returncode}")
            elif args.copy_glb_without_blender:
                fallback_copy_glb(source, output_glb=output_glb, metadata_out=metadata_out)
                stdout_log.write_text("fallback copy mode", encoding="utf-8")
                stderr_log.write_text("", encoding="utf-8")
            else:
                raise FileNotFoundError(
                    f"Blender executable not found: '{blender_exe}'. "
                    "Set --blender-exe or use --copy-glb-without-blender for .glb passthrough."
                )

            metadata = {}
            if metadata_out.exists():
                metadata = json.loads(metadata_out.read_text(encoding="utf-8"))
            animated = bool(metadata.get("has_armature", False))
            mesh_vertices = int(metadata.get("mesh_vertices", 0) or 0)

            if not output_glb.exists():
                raise FileNotFoundError(f"worker did not produce output glb: {output_glb}")
            if output_glb.stat().st_size <= 0:
                raise RuntimeError(f"worker produced empty output glb: {output_glb}")
            if mesh_vertices <= 0:
                raise RuntimeError(f"worker metadata has invalid mesh vertex count ({mesh_vertices}): {metadata_out}")

            xmodel_path = xmodel_dir / f"{name}.json"
            write_xmodel_descriptor(
                path=xmodel_path,
                model_file_rel=f"model_export/{glb_name}",
                animated=animated,
            )
            xmodel_names.append(name)

            row.update(
                {
                    "status": "ok",
                    "xmodel_json": str(xmodel_path),
                    "glb": str(output_glb),
                    "metadata": metadata,
                }
            )
        except Exception as exc:  # pragma: no cover - per-asset fault tolerance
            row.update({"status": "error", "error": str(exc)})

        rows.append(row)
        if idx % 25 == 0:
            print(f"processed {idx}/{len(files)}")

    write_zone_file(project_root / "zone_source" / f"{project}.zone", xmodel_names=xmodel_names)

    report = {
        "project": project,
        "input": str(input_path),
        "output_project_root": str(project_root),
        "blender_executable": blender_exe,
        "skeleton_map": str(skeleton_map),
        "settings": {
            "decimate_ratio": float(args.decimate_ratio),
            "max_bones": int(args.max_bones),
            "max_weights": int(args.max_weights),
            "max_submesh_vertices": int(args.max_submesh_vertices),
            "verbose_worker": bool(args.verbose_worker),
        },
        "counts": {
            "input_files": len(files),
            "ok": sum(1 for row in rows if row["status"] == "ok"),
            "error": sum(1 for row in rows if row["status"] == "error"),
        },
        "rows": rows,
    }

    report_path = Path(args.report)
    if not report_path.is_absolute():
        report_path = (repo_root / report_path).resolve()
    save_json(report_path, report)
    print(f"Saved conversion report: {report_path}")
    print(
        f"Converted: ok={report['counts']['ok']} "
        f"error={report['counts']['error']} "
        f"project_root={project_root}"
    )


if __name__ == "__main__":
    main()
