from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Set

SCRIPT_DIR = Path(__file__).resolve().parent

import sys

if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from common import save_json  # noqa: E402
from map_port_common import ASSET_TYPE_DIRS, sanitize_name  # noqa: E402


def token_for_zone(asset_type: str) -> str:
    normalized = asset_type.strip().lower()
    if normalized == "techset":
        return "techniqueset"
    if normalized == "xmodelalias":
        return "xmodel"
    if normalized == "xanimparts":
        return "xanim"
    return normalized


def relative_from_type_dir(src_path: Path, type_dirs: Sequence[str]) -> Path:
    type_set = {name.lower() for name in type_dirs}
    for idx, part in enumerate(src_path.parts):
        lower = part.lower()
        if lower in type_set:
            return Path(*src_path.parts[idx + 1 :])
    return Path(src_path.name)


def destination_for_asset(project_zone_root: Path, asset_type: str, src_path: Path, project_name: str) -> Path:
    normalized = asset_type.lower()
    if normalized == "mapents":
        return project_zone_root / "maps" / "mp" / f"{project_name}.d3dbsp.ents"

    dirs = ASSET_TYPE_DIRS.get(normalized, [])
    if not dirs:
        return project_zone_root / normalized / src_path.name

    primary = dirs[0]
    rel = relative_from_type_dir(src_path, dirs)
    return project_zone_root / primary / rel


def resolve_model_export_source(source_zone_root: Path, xmodel_src: Path, lod_file: str) -> Optional[Path]:
    rel = Path(lod_file)
    candidates = [
        xmodel_src.parent / rel,
        xmodel_src.parent.parent / rel,
        source_zone_root / rel,
        source_zone_root / "model_export" / rel.name,
    ]
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def stage_xmodel_lods(source_zone_root: Path, project_zone_root: Path, xmodel_dst: Path) -> Dict[str, Any]:
    payload = json.loads(xmodel_dst.read_text(encoding="utf-8"))
    lods = payload.get("lods", [])
    if not isinstance(lods, list):
        return {"copied_lods": [], "missing_lods": []}

    copied_lods: List[str] = []
    missing_lods: List[str] = []
    for lod in lods:
        if not isinstance(lod, dict):
            continue
        file_field = str(lod.get("file", "")).strip()
        if not file_field:
            continue

        src_lod = resolve_model_export_source(source_zone_root, xmodel_dst, file_field)
        if src_lod is None:
            missing_lods.append(file_field)
            continue

        dst_lod = project_zone_root / "model_export" / src_lod.name
        dst_lod.parent.mkdir(parents=True, exist_ok=True)
        if not dst_lod.exists():
            shutil.copy2(src_lod, dst_lod)
        lod["file"] = f"model_export/{dst_lod.name}"
        copied_lods.append(str(dst_lod))

    xmodel_dst.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return {"copied_lods": copied_lods, "missing_lods": missing_lods}


def write_zone_file(zone_path: Path, project_name: str, lines: List[str]) -> None:
    zone_path.parent.mkdir(parents=True, exist_ok=True)
    text = ["// Auto-generated by bootstrap_map_port_project.py", ">game,T6", ""]
    text.extend(lines)
    zone_path.write_text("\n".join(text).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Bootstrap map port project from map plan.")
    parser.add_argument("--plan", required=True, help="Input map port plan JSON.")
    parser.add_argument("--output-root", default="_build/asset_port_pipeline/map_port_projects", help="Output root.")
    parser.add_argument("--project-name", required=True, help="Output BO2 project/map name.")
    parser.add_argument(
        "--include-phases",
        nargs="*",
        default=["core_map", "render_assets", "gameplay_assets", "scripts"],
        help="Plan phases to include in project bootstrap.",
    )
    parser.add_argument("--max-assets", type=int, default=0, help="Optional global cap for quick bootstrap runs.")
    parser.add_argument("--only-bo2-missing", action="store_true", help="Only include assets missing from BO2 references.")
    parser.add_argument("--keep-missing-zone-lines", action="store_true", help="Keep zone entries even when source asset was not copied.")
    parser.add_argument("--output-report", default="_build/asset_port_pipeline/map_bootstrap_report.json", help="Output report JSON.")
    args = parser.parse_args()

    repo_root = Path.cwd().resolve()
    plan_path = Path(args.plan)
    if not plan_path.is_absolute():
        plan_path = (repo_root / plan_path).resolve()
    if not plan_path.exists():
        raise FileNotFoundError(f"Plan not found: {plan_path}")

    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    entries: List[Dict[str, Any]] = plan.get("entries", [])
    if not entries:
        raise RuntimeError("Plan has no entries.")
    source_zone_root = Path(str(plan.get("source_zone_root", ""))).resolve()
    if not source_zone_root.exists():
        raise FileNotFoundError("Plan source_zone_root is missing or invalid.")

    project_name = sanitize_name(args.project_name)
    output_root = Path(args.output_root)
    if not output_root.is_absolute():
        output_root = (repo_root / output_root).resolve()
    project_root = output_root / project_name
    project_zone_root = project_root / "zone_raw" / project_name
    project_zone_root.mkdir(parents=True, exist_ok=True)

    include_phases = {item.strip().lower() for item in args.include_phases if item.strip()}
    selected: List[Dict[str, Any]] = []
    for item in entries:
        phase = str(item.get("phase", "")).lower()
        if phase not in include_phases:
            continue
        if args.only_bo2_missing and bool(item.get("bo2_found", False)):
            continue
        selected.append(item)
        if args.max_assets > 0 and len(selected) >= args.max_assets:
            break

    copied_rows: List[Dict[str, Any]] = []
    missing_rows: List[Dict[str, Any]] = []
    zone_lines: List[str] = []
    seen_zone_lines: Set[str] = set()

    for item in selected:
        asset_type = str(item.get("asset_type", "")).strip().lower()
        asset_name = str(item.get("asset_name", "")).strip()
        source_path = str(item.get("source_path", "")).strip()

        if not asset_type or not asset_name:
            continue

        zone_token = token_for_zone(asset_type)
        zone_asset_name = project_name if asset_type == "mapents" else asset_name
        if not source_path:
            if args.keep_missing_zone_lines:
                line = f"{zone_token},{zone_asset_name}"
                if line.lower() not in seen_zone_lines:
                    seen_zone_lines.add(line.lower())
                    zone_lines.append(line)
            missing_rows.append({**item, "reason": "source_path_missing"})
            continue

        src = Path(source_path)
        if not src.exists():
            if args.keep_missing_zone_lines:
                line = f"{zone_token},{zone_asset_name}"
                if line.lower() not in seen_zone_lines:
                    seen_zone_lines.add(line.lower())
                    zone_lines.append(line)
            missing_rows.append({**item, "reason": "source_path_not_found"})
            continue

        dst = destination_for_asset(project_zone_root, asset_type=asset_type, src_path=src, project_name=project_name)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

        lod_stage = {"copied_lods": [], "missing_lods": []}
        if asset_type == "xmodel":
            lod_stage = stage_xmodel_lods(source_zone_root=source_zone_root, project_zone_root=project_zone_root, xmodel_dst=dst)

        line = f"{zone_token},{zone_asset_name}"
        if line.lower() not in seen_zone_lines:
            seen_zone_lines.add(line.lower())
            zone_lines.append(line)
        copied_rows.append(
            {
                "asset_type": asset_type,
                "asset_name": asset_name,
                "source": str(src),
                "destination": str(dst),
                "copied_lods": lod_stage["copied_lods"],
                "missing_lods": lod_stage["missing_lods"],
            }
        )

    zone_path = project_root / "zone_source" / f"{project_name}.zone"
    write_zone_file(zone_path, project_name=project_name, lines=zone_lines)

    report = {
        "generated_at_utc": dt.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "plan": str(plan_path),
        "project_name": project_name,
        "project_root": str(project_root),
        "zone_file": str(zone_path),
        "ipak_reads_from_plan": plan.get("ipak_reads", []),
        "include_phases": sorted(include_phases),
        "only_bo2_missing": bool(args.only_bo2_missing),
        "keep_missing_zone_lines": bool(args.keep_missing_zone_lines),
        "counts": {
            "plan_entries": len(entries),
            "selected_entries": len(selected),
            "copied": len(copied_rows),
            "missing": len(missing_rows),
            "zone_lines": len(zone_lines),
        },
        "copied": copied_rows,
        "missing": missing_rows[:500],
    }

    report_path = Path(args.output_report)
    if not report_path.is_absolute():
        report_path = (repo_root / report_path).resolve()
    save_json(report_path, report)

    print(f"Saved map bootstrap report: {report_path}")
    print(
        f"selected={report['counts']['selected_entries']} "
        f"copied={report['counts']['copied']} "
        f"missing={report['counts']['missing']} "
        f"zone_lines={report['counts']['zone_lines']}"
    )


if __name__ == "__main__":
    main()
